name: Build and Deploy to sigrasamyak.com

on:
  # Trigger manually
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository with React code'
        required: true
        default: 'YourUsername/source-repo-name'
      source_branch:
        description: 'Branch containing the source code'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository (GitHub Pages repo)
        uses: actions/checkout@v3
        
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: ${{ github.event.inputs.source_branch }}
          path: source-repo
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install and Build
        working-directory: ./source-repo
        run: |
          npm ci
          npm run build
          
      - name: Copy build files to root
        run: |
          # Remove everything except .git, workflow files, and CNAME
          find . -maxdepth 1 -not -path "./source-repo" -not -path "./.git" -not -path "./.github" -not -path "." -not -name "CNAME" | xargs rm -rf
          
          # Copy build files from source repository
          cp -r source-repo/dist/* .
          
          # Clean up source repository
          rm -rf source-repo
          
      - name: Ensure CNAME file exists
        run: |
          echo "sigrasamyak.com" > CNAME
        
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update from React build" || echo "No changes to commit"
          
          # Use the PAT token for push authentication
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main
